name: Playwright Tests  
on:  
  push:  
    branches: [ main, master ]  
  pull_request:  
    branches: [ main, master ]  
  
jobs:  
  playwright:  
    name: 'Playwright Tests'  
    runs-on: ubuntu-latest  
    container:  
      image: mcr.microsoft.com/playwright/python:v1.44.0-jammy  
    steps:  
      - uses: actions/checkout@v3  
  
      # 安装依赖项  
      - name: Install dependencies  
        run: |  
          pip install --upgrade pip  
          pip install -r requirements.txt  # 假设文件名是requirements.txt  
          # pip install -e .  # 如果你有一个可编辑的安装需求，可以取消注释这行  
   
      # 运行测试  
      - name: Run Playwright tests  
        run: pytest  
