name: Playwright Tests  
on:  
  push:  
    branches: [ main, master ]  
  pull_request:  
    branches: [ main, master ]  
  
jobs:  
  playwright:  
    name: 'Playwright Tests'  
    runs-on: ubuntu-latest  
    container:  
      image: mcr.microsoft.com/playwright/python:v1.44.0-jammy  
    steps:  
      - uses: actions/checkout@v4  
  
      # 设置Python版本  
      - name: Set up Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: '3.11'  
  
      # 创建虚拟环境  
      - name: Create virtual environment  
        run: python -m venv venv  
  
      # 激活虚拟环境  
      - name: Activate virtual environment  
        run: source venv/bin/activate  
  
      # 安装依赖项  
      - name: Install dependencies  
        run: |  
          pip install --upgrade pip  
          pip install -r requirements.txt  # 假设文件名是requirements.txt  
          pip install -e .  # 如果你有一个可编辑的安装需求  
   
      # 运行测试  
      - name: Run Playwright tests  
        run: pytest  
